queue_rules:
  - name: default
    queue_conditions:
      - author=scala-steward
      - check-success=test
    merge_conditions:
      - "check-success=test"
    merge_method: merge

pull_request_rules:
  - name: Merge passing scala-steward PRs
    conditions:
      - author=scala-steward
      - check-success=test
    actions:
      review:
        type: APPROVE
      delete_head_branch: {}
      queue:
