queue_rules:
  - name: default
    conditions:
      - "check-success=Test / test (pull_request)"

pull_request_rules:
  - name: Merge passing scala-steward PRs
    conditions:
      - author=scala-steward
      - "check-success=Test / test (pull_request)"
    actions:
      review:
        type: APPROVE
      queue:
        method: merge
        name: default
      delete_head_branch: {}
