name: Test Code + Build Docker Image
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: scalafmtCheckAll
      run: sbt scalafmtCheckAll
    - name: Test
      run: sbt test
    - name: Build
      run: sbt "Docker / publishLocal"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Tag
      run: docker tag recibase:latest ghcr.io/the-silverwood-institute/recibase:latest
    - name: Docker Push
      run: docker push ghcr.io/the-silverwood-institute/recibase:latest
    - name: Trigger Render Deployment
      run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}&ref=${{ github.sha }}"
